"""Standalone featurization of 1UBQ_A using ONLY boltz_jax.data (no import boltz).

Loads the precomputed processed structure/record for 1UBQ_A produced by the
original Boltz pipeline, runs the COPIED Boltz2Tokenizer + Boltz2Featurizer via
the copied PredictionDataset, and compares against the reference feature dict
outputs/real_features/1UBQ_A.npz.

Run:
  JAX_PLATFORMS=cpu uv run --extra torch-bridge python scripts/featurize_standalone.py
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import torch

# Hard guard: this pipeline must be self-contained.
assert "boltz" not in sys.modules

from boltz_jax.data.module.inferencev2 import PredictionDataset  # noqa: E402
from boltz_jax.data.types import Manifest  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
BOLTZ_ROOT = ROOT.parent / "boltz"

# Processed tree for 1UBQ_A (no-MSA) generated by the original boltz CLI.
PROCESSED = (
    BOLTZ_ROOT
    / "benchmark_results"
    / "real_pdb_eval_expanded_2026-06-04"
    / "boltz_results_inputs"
    / "processed"
)
MOL_DIR = BOLTZ_ROOT / ".cache" / "boltz" / "mols"
REF_NPZ = ROOT / "outputs" / "real_features" / "1UBQ_A.npz"
RECORD_ID = "1UBQ_A"


def build_features() -> dict[str, np.ndarray]:
    assert PROCESSED.exists(), f"missing processed tree: {PROCESSED}"
    assert MOL_DIR.exists(), f"missing mols dir: {MOL_DIR}"

    full = Manifest.load(PROCESSED / "manifest.json")
    # Keep only the 1UBQ_A record (Manifest is frozen -> build a new one).
    records = [r for r in full.records if r.id == RECORD_ID]
    assert len(records) == 1, f"record {RECORD_ID} not in manifest"
    manifest = Manifest(records=records)

    dataset = PredictionDataset(
        manifest=manifest,
        target_dir=PROCESSED / "structures",
        msa_dir=PROCESSED / "msa",
        mol_dir=MOL_DIR,
        constraints_dir=PROCESSED / "constraints",
        template_dir=PROCESSED / "templates",
        extra_mols_dir=PROCESSED / "mols",
    )
    features = dataset[0]

    # Match reference layout: leading batch dim 1, drop private/non-tensor keys.
    feats_np: dict[str, np.ndarray] = {}
    for key, value in features.items():
        if key.startswith("_") or key == "record":
            continue
        if not torch.is_tensor(value):
            continue
        feats_np[key] = value.unsqueeze(0).detach().cpu().numpy()
    return feats_np


def _ref_pos_rigid_match(produced: dict, ref: dict) -> tuple[bool, str]:
    """ref_pos is randomly roto-translated per ref_space_uid block via an
    UNSEEDED torch.randn (featurizerv2: center_random_augmentation), so the raw
    values are not reproducible. Verify the conformer geometry instead: intra-
    block pairwise distances of resolved atoms must match (rigid invariance)."""
    rp_r, rp_o = ref["ref_pos"][0], produced["ref_pos"][0]
    if rp_r.shape != rp_o.shape:
        return False, f"shape {rp_o.shape} vs {rp_r.shape}"
    uid = ref["ref_space_uid"][0]
    res = ref["atom_resolved_mask"][0].astype(bool)

    def pdist(x):
        d = x[:, None, :] - x[None, :, :]
        return np.sqrt((d * d).sum(-1))

    worst = 0.0
    for u in np.unique(uid):
        idx = np.where((uid == u) & res)[0]
        if len(idx) < 2:
            continue
        worst = max(worst, float(np.abs(pdist(rp_r[idx]) - pdist(rp_o[idx])).max()))
    ok = worst < 1e-3
    return ok, f"rigid-invariant: intra-block dist max|d|={worst:.2e} (RNG aug)"


def compare(produced: dict[str, np.ndarray], ref: dict[str, np.ndarray]) -> bool:
    pk, rk = set(produced), set(ref)
    missing = sorted(rk - pk)
    extra = sorted(pk - rk)

    rows = []
    overall = True
    for k in sorted(rk & pk):
        if k == "ref_pos":
            ok, detail = _ref_pos_rigid_match(produced, ref)
            rows.append((k, "PASS" if ok else "FAIL", detail))
            overall = overall and ok
            continue
        a, b = produced[k], ref[k]
        shape_ok = a.shape == b.shape
        if not shape_ok:
            rows.append((k, "FAIL", f"shape {a.shape} vs {b.shape}"))
            overall = False
            continue
        if np.issubdtype(b.dtype, np.floating):
            close = np.allclose(a, b, atol=1e-4, equal_nan=True)
            detail = "" if close else f"max|d|={np.nanmax(np.abs(a - b)):.3e}"
        else:
            close = np.array_equal(a, b)
            detail = "" if close else "int mismatch"
        rows.append((k, "PASS" if close else "FAIL", detail))
        overall = overall and close

    w = max(len(r[0]) for r in rows) if rows else 10
    print(f"{'key':<{w}}  RESULT  detail")
    print("-" * (w + 25))
    for k, res, detail in rows:
        print(f"{k:<{w}}  {res:<6}  {detail}")

    if missing:
        overall = False
        print(f"\nMISSING keys (in ref, not produced): {missing}")
    if extra:
        print(f"\nEXTRA keys (produced, not in ref): {extra}")

    n_pass = sum(1 for _, r, _ in rows if r == "PASS")
    print(f"\n{n_pass}/{len(rows)} matched keys PASS; "
          f"{len(missing)} missing, {len(extra)} extra")
    return overall and not missing


def main() -> None:
    assert REF_NPZ.exists(), f"missing reference npz: {REF_NPZ}"
    ref = dict(np.load(REF_NPZ))
    produced = build_features()
    print(f"produced {len(produced)} keys; reference {len(ref)} keys\n")
    overall = compare(produced, ref)
    print("\nOVERALL:", "PASS" if overall else "FAIL")
    sys.exit(0 if overall else 1)


if __name__ == "__main__":
    main()
